### ISSUE TITLE
Update dataflow-timeseries-samples-library to use latest and install from maven

### ISSUE THREAD

**Issue by JJ11teen** [kasna-cloud/dataflow-fsi-example#11]

**Comment by troybebee** [comment]
Library updates have broken the build/deploy. Failure is here:

`apache_beam.coders.coder_impl.FastPrimitivesCoderImpl.encode_special_deterministic TypeError: Unable to deterministically encode '<TableReference datasetId: 'forex' projectId: 'fsi-demo-pres' tableId: 'prices'>' of type '<class 'apache_beam.io.gcp.internal.clients.bigquery.bigquery_v2_messages.TableReference'>', please provide a type hint for the input of 'Write to BigQuery (prices)/_StreamToBigQuery/CommitInsertIds/GroupByKey' [while running 'Write to BigQuery (prices)/_StreamToBigQuery/CommitInsertIds/Map(reify_timestamps)-ptransform-1768936'] passed through: ==> dist_proc/dax/workflow/worker/fnapi_service_impl.cc:644 generic::unknown: Traceback (most recent call last): File`

**Comment by viohman** [comment]
Pull request:
 python beam sdk update -> 2.30.0 #18
